language: elixir

elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.2
  - 1.9.1

otp_release:
  - 20.3
  - 21.3
  - 22.1

dist: xenial
sudo: required

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libzmq3-dev
      - python-dev
      - python3-pip
      - python3-setuptools

before_install:
  - ./_download_rebar3.sh
  - '[[ $TRAVIS_BRANCH == master ]] || ./_checkout_jupyter.sh'

install:
  - sudo pip3 install -U jupyter_kernel_test
  - sudo pip3 install -U pytest
  - ./rebar3 get-deps

script:
  # Ignore xref results
  - './rebar3 xref || true'
  - ./rebar3 dialyzer
  - ./test.sh
